---
jobs:
  - name: cuda-nvidia-smi-test
    plan:
      - task: run-nvidia-smi
        tags: [gpu]
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: nvidia/cuda
              tag: 13.1.0-base-ubuntu24.04
          run:
            path: sh
            args:
              - -c
              - |
                FAILED=0
                
                echo "========================================="
                echo "NVIDIA CUDA + Dataset Test"
                echo "========================================="
                echo ""
                
                echo "1. NVIDIA SMI Test:"
                if nvidia-smi; then
                  echo "✅ nvidia-smi passed"
                  echo "Location: $(which nvidia-smi)"
                else
                  echo "❌ nvidia-smi failed"
                  echo "which nvidia-smi: $(which nvidia-smi 2>&1 || echo 'not found')"
                  echo "PATH check: $PATH"
                  FAILED=1
                fi
                echo ""
                
                echo "2. CUDA Version Check:"
                if [ -n "$CUDA_VERSION" ]; then
                  echo "CUDA_VERSION environment variable: $CUDA_VERSION"
                  echo "✅ CUDA version available"
                else
                  echo "❌ CUDA_VERSION environment variable not set"
                  FAILED=1
                fi
                echo ""
                
                echo "Environment Variables:"
                printenv | sort
                echo ""
                
                echo "3. NVIDIA Driver Version:"
                if cat /proc/driver/nvidia/version 2>/dev/null; then
                  echo "✅ Driver info accessible"
                else
                  echo "❌ Driver info not accessible"
                  FAILED=1
                fi
                echo ""
                
                echo "4. Dataset Access Test:"
                if [ -d /srv/datasets ]; then
                  DATASET_COUNT=$(ls -1 /srv/datasets 2>/dev/null | wc -l)
                  echo "✅ Found $DATASET_COUNT items in /srv/datasets"
                  echo ""
                  echo "First 20 items:"
                  ls -lah /srv/datasets/ | head -20
                else
                  echo "❌ /srv/datasets not found"
                  FAILED=1
                fi
                echo ""
                
                echo "5. Dataset Write Test (should fail - read-only):"
                if touch /srv/datasets/test-write 2>&1; then
                  echo "❌ Write succeeded - mount is NOT read-only"
                  FAILED=1
                else
                  echo "✅ Confirmed read-only mount"
                fi
                echo ""
                
                echo "========================================="
                if [ $FAILED -eq 0 ]; then
                  echo "✅ CUDA test completed successfully!"
                  echo "========================================="
                  exit 0
                else
                  echo "❌ CUDA test completed with failures!"
                  echo "========================================="
                  exit 1
                fi
